services:
  cloudflared:
    image: cloudflare/cloudflared:2026.10.0
    command: [tunnel, --no-autoupdate, --config, /etc/cloudflared/config.yml, run]
    volumes: ['./.data/cloudflared/config.yml:/etc/cloudflared/config.yml:ro','./.data/cloudflared/credentials.json:/etc/cloudflared/credentials.json:ro']
    depends_on: [web,api,storage]
    restart: unless-stopped
