import React,{useState,createContext,useContext} from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter,Routes,Route,NavLink,Link,Navigate,Outlet } from 'react-router-dom';
import { Compass,FolderOpen,Layers,LogOut,Smartphone,ArrowRight } from 'lucide-react';
import { api,post,type Settings } from './api';
import { useResource } from './hooks';
import { Loading,Notice } from './components';
import { Catalog,Details,Projects,ImportReview,ProjectEditor,Jobs,LauncherDashboard,DiagnosticsPage,PerformancePage } from './pages';
import './styles.css';
const SettingsContext=createContext<Settings>({curseforgeConfigured:false,buildEnabled:false,validatedTargets:[]});
export const useSettings=()=>useContext(SettingsContext);
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login-page"><div className="login-brand"><div className="brand-mark"><Layers/></div><h1>Pojav <span>Studio</span></h1><p>Seu próximo modpack começa aqui.</p></div><form className="login-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await post('/auth/login',{email,password});window.location.assign('/catalog/modpacks');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h2>Entrar no painel</h2><p>Acesso exclusivo para administradores.</p>{error&&<Notice>{error}</Notice>}<label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Entrando...':'Entrar'}<ArrowRight size={18}/></button></form><div className="login-foot">Modpacks de qualquer origem. Um destino: Android.</div></div>;}
function Session(){const me=useResource<{email:string}>('/auth/me'),settings=useResource<Settings>('/settings');if(me.loading)return <Loading label="Abrindo o Studio..."/>;if(me.error)return <Login/>;return <SettingsContext.Provider value={settings.data??{curseforgeConfigured:false,buildEnabled:false,validatedTargets:[]}}><div className="app-shell"><aside className="sidebar"><Link className="brand" to="/catalog/modpacks"><div className="brand-mark"><Layers size={23}/></div><span>Pojav<strong>STUDIO</strong></span></Link><span className="nav-label">BIBLIOTECA</span><nav><NavLink to="/catalog/modpacks"><Compass size={19}/>Explorar Modpacks</NavLink><NavLink to="/projects"><FolderOpen size={19}/>Meus Modpacks</NavLink><NavLink to="/launcher"><Smartphone size={19}/>Launcher Android</NavLink><NavLink to="/diagnostics"><Layers size={19}/>Relatórios de erro</NavLink><NavLink to="/jobs"><Layers size={19}/>Atividade</NavLink></nav><div className="sidebar-bottom"><div className="android-note"><Smartphone size={20}/><div>Feito para Android<small>Pojav / Amethyst</small></div></div><button className="account" onClick={async()=>{await post('/auth/logout');window.location.assign('/');}}><span>{me.data?.email}</span><LogOut size={17}/></button></div></aside><main><header className="topbar"><span>WORKSPACE <span className="separator">/</span> <strong>Modpack Studio</strong></span><span className="admin-pill">Administrador</span></header><div className="page-content"><Outlet/></div></main></div></SettingsContext.Provider>;}
function App(){return <BrowserRouter><Routes><Route element={<Session/>}><Route index element={<Navigate to="/catalog/modpacks" replace/>}/><Route path="catalog/modpacks" element={<Catalog/>}/><Route path="catalog/modpacks/:provider/:id" element={<Details/>}/><Route path="projects" element={<Projects/>}/><Route path="projects/:id/performance" element={<PerformancePage/>}/><Route path="projects/:id" element={<ProjectEditor/>}/><Route path="imports/:id" element={<ImportReview/>}/><Route path="launcher" element={<LauncherDashboard/>}/><Route path="diagnostics" element={<DiagnosticsPage/>}/><Route path="jobs" element={<Jobs/>}/><Route path="*" element={<Navigate to="/catalog/modpacks" replace/>}/></Route></Routes></BrowserRouter>;}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
