import { randomUUID, createHash } from 'node:crypto';
import { ConflictException, BadRequestException } from '@nestjs/common';
import { z } from 'zod';
import { bundleSchema, deduplicate, diffFiles, mergeUpstream, runtimeFor, safePath, type Bundle, type ImportedFrom, type ReleaseManifest } from '@studio/core';
import { env } from '../config.js';
import { db, builds, objectUrl, putObject, hasObject } from '../infra.js';
import { compatible, providers } from '../providers/registry.js';
import { json, queueImport } from './jobs.js';
import type { PreparedImport } from '../importer/process.js';
const nameSchema=z.string().trim().min(1).max(120);
export const commitSchema=z.object({name:nameSchema,optionalFiles:z.array(z.string()).default([])});
const editSchema=z.object({revision:z.number().int().positive(),name:nameSchema.optional(),customVersion:z.string().trim().min(1).max(100).optional(),icon:z.string().refine(x=>/^\/api\/v1\/public\/icons\/[a-f0-9]{64}$/.test(x)).nullable().optional(),removeFileIds:z.array(z.string()).optional(),requiredFiles:z.array(z.string()).optional(),performanceEnabled:z.boolean().optional()});
export async function saveRevision(projectId:string,revision:number,bundle:Bundle,reason:string,extra:{name?:string;icon?:string|null;customVersion?:string;importedFrom?:ImportedFrom;upstreamSnapshot?:Bundle}={}){
  return db.$transaction(async tx=>{
    const project=await tx.project.findUniqueOrThrow({where:{id:projectId}});const snapshot=(extra.upstreamSnapshot??project.upstreamSnapshot) as unknown as Bundle|null;
    const upstream=(extra.importedFrom??project.importedFrom) as unknown as ImportedFrom|null;
    const modified=!!snapshot&&(diffFiles(bundleSchema.parse(snapshot).files,bundle.files).length>0||bundle.minecraft!==snapshot.minecraft||bundle.loader.type!==snapshot.loader.type||bundle.loader.version!==snapshot.loader.version||JSON.stringify(bundle.performance)!==JSON.stringify(bundleSchema.parse(snapshot).performance)||(extra.name??project.name)!==upstream?.name);
    const {importedFrom,upstreamSnapshot,...fields}=extra;
    const updated=await tx.project.updateMany({where:{id:projectId,revision},data:{...fields,draft:json(bundle),modified,revision:{increment:1},...(importedFrom?{importedFrom:json(importedFrom)}:{}),...(upstreamSnapshot?{upstreamSnapshot:json(upstreamSnapshot)}:{})}});
    if(!updated.count)throw new ConflictException('O projeto mudou. Recarregue antes de salvar.');
    await tx.revision.create({data:{projectId,number:revision+1,draft:json(bundle),reason}});await tx.audit.create({data:{action:reason,entityId:projectId,detail:json({revision:revision+1})}});return tx.project.findUniqueOrThrow({where:{id:projectId}});
  });
}
export async function commitImport(jobId:string,input:unknown){const options=commitSchema.parse(input);return db.$transaction(async tx=>{
  const job=await tx.job.findUniqueOrThrow({where:{id:jobId}});if(job.kind!=='prepare'||job.status!=='ready'||!job.result)throw new BadRequestException('Importação ainda não está pronta');
  const prepared=job.result as unknown as PreparedImport;const bundle=bundleSchema.parse(prepared.bundle);const baseline=structuredClone(bundle);
  bundle.name=options.name;const selected=new Set(bundle.files.filter(f=>f.required||options.optionalFiles.includes(f.id)).map(f=>f.id));let grew=true;while(grew){grew=false;for(const file of bundle.files)if(!selected.has(file.id)&&file.requiredBy.some(parent=>selected.has(parent))){selected.add(file.id);grew=true;}}bundle.files=bundle.files.filter(f=>selected.has(f.id));for(const file of bundle.files)file.required=true;
  const slug=options.name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,60).replace(/^-|-$/g,'')||'modpack';
  const consumed=await tx.job.updateMany({where:{id:jobId,status:'ready'},data:{status:'committed'}});if(!consumed.count)throw new ConflictException('Importação já utilizada');
  const project=await tx.project.create({data:{name:options.name,slug:`${slug}-${randomUUID().slice(0,8)}`,icon:prepared.icon,draft:json(bundle),...(prepared.importedFrom?{importedFrom:json(prepared.importedFrom),upstreamSnapshot:json(baseline),modified:options.name!==prepared.importedFrom.name||diffFiles(baseline.files,bundle.files).length>0}:{})}});
  await tx.revision.create({data:{projectId:project.id,number:1,draft:json(bundle),reason:'import'}});await tx.job.update({where:{id:jobId},data:{projectId:project.id}});await tx.audit.create({data:{action:'import',entityId:project.id,detail:json({jobId})}});return project;
});}
export async function editProject(id:string,input:unknown){const edit=editSchema.parse(input);const project=await db.project.findUniqueOrThrow({where:{id}});const bundle=bundleSchema.parse(project.draft);if(edit.name)bundle.name=edit.name;if(edit.performanceEnabled!==undefined)bundle.performance.enabled=edit.performanceEnabled;if(edit.removeFileIds){bundle.files=bundle.files.filter(f=>!edit.removeFileIds!.includes(f.id));for(const file of bundle.files)if(file.kind==='mod'){file.status='pending';file.issue='Verifique as depend?ncias ap?s remover arquivos';}}if(edit.requiredFiles)for(const file of bundle.files)file.required=edit.requiredFiles.includes(file.id);return saveRevision(id,edit.revision,bundle,'edit',{name:edit.name,icon:edit.icon,customVersion:edit.customVersion});}
export async function applyPrepared(id:string,jobId:string){const job=await db.job.findUniqueOrThrow({where:{id:jobId}});const input=job.input as {targetProjectId?:string;revision?:number};if(job.status!=='ready'||input.targetProjectId!==id||!input.revision||!['add-mod','verify-draft'].includes(job.kind))throw new BadRequestException('Job incompatível com este projeto');const prepared=job.result as unknown as PreparedImport;const project=await db.project.findUniqueOrThrow({where:{id}});const current=bundleSchema.parse(project.draft);if(job.kind==='add-mod'){const merged=deduplicate([...current.files,...prepared.bundle.files]);current.files=merged.files;current.warnings.push(...merged.warnings);}else current.files=prepared.bundle.files;
  const saved=await saveRevision(id,input.revision,current,job.kind);await db.job.update({where:{id:jobId},data:{status:'committed'}});return saved;}
export async function checkUpstream(id:string){const project=await db.project.findUniqueOrThrow({where:{id}});const origin=project.importedFrom as unknown as ImportedFrom|null;if(!origin)throw new BadRequestException('Projeto não possui upstream');const bundle=bundleSchema.parse(project.draft);const versions=await providers[origin.provider].getVersions(origin.projectId,{minecraft:bundle.minecraft,loader:bundle.loader.type});const installed=await providers[origin.provider].getVersion(origin.projectId,origin.versionId);const candidates=versions.filter(v=>v.id!==origin.versionId&&v.publishedAt>installed.publishedAt);return {installed,newest:candidates[0]??null,versions:candidates};}
export async function prepareUpstream(id:string,versionId:string){const project=await db.project.findUniqueOrThrow({where:{id}});const origin=project.importedFrom as unknown as ImportedFrom|null;if(!origin)throw new BadRequestException('Sem upstream');return queueImport({provider:origin.provider,projectId:origin.projectId,versionId,targetProjectId:id,revision:project.revision,operation:'upstream'});}
export async function upstreamDiff(id:string,jobId:string){const project=await db.project.findUniqueOrThrow({where:{id}});const job=await db.job.findUniqueOrThrow({where:{id:jobId}});const input=job.input as {targetProjectId?:string;revision?:number};if(job.status!=='ready'||job.kind!=='upstream'||input.targetProjectId!==id)throw new BadRequestException('Diff indisponível');if(input.revision!==project.revision)throw new ConflictException('Projeto mudou durante a análise. Prepare novamente.');const prepared=job.result as unknown as PreparedImport;const base=bundleSchema.parse(project.upstreamSnapshot),local=bundleSchema.parse(project.draft);const result=mergeUpstream(base.files,local.files,prepared.bundle.files);return {...result,installed:base.version,newVersion:prepared.bundle.version,jobId,revision:project.revision};}
export async function applyUpstream(id:string,input:unknown){const {jobId,choices}=z.object({jobId:z.string(),choices:z.record(z.enum(['local','upstream'])).default({})}).parse(input);await upstreamDiff(id,jobId);const project=await db.project.findUniqueOrThrow({where:{id}});const job=await db.job.findUniqueOrThrow({where:{id:jobId}});const prepared=job.result as unknown as PreparedImport;const base=bundleSchema.parse(project.upstreamSnapshot),local=bundleSchema.parse(project.draft);const merged=mergeUpstream(base.files,local.files,prepared.bundle.files,choices);if(merged.conflicts.length)throw new ConflictException('Escolha uma resolução para todos os conflitos');local.files=deduplicate(merged.files).files;local.version=prepared.bundle.version;local.minecraft=prepared.bundle.minecraft;local.loader=prepared.bundle.loader;const saved=await saveRevision(id,project.revision,local,'upstream-update',{importedFrom:prepared.importedFrom!,upstreamSnapshot:prepared.bundle});await db.job.update({where:{id:jobId},data:{status:'committed'}});return saved;}
export async function addLocalFile(id:string,revision:number,path:string,bytes:Buffer){safePath(path);const project=await db.project.findUniqueOrThrow({where:{id}});const bundle=bundleSchema.parse(project.draft);
  const {resolvedFileSchema,kindFor}=await import('@studio/core');const sha256=createHash('sha256').update(bytes).digest('hex');const key=await putObject(`assets/${sha256}`,bytes);
  bundle.files.push(resolvedFileSchema.parse({id:randomUUID(),provider:'local',name:path.split('/').at(-1),filename:path.split('/').at(-1),path,hashes:{sha256,sha1:createHash('sha1').update(bytes).digest('hex'),sha512:createHash('sha512').update(bytes).digest('hex')},size:bytes.length,kind:kindFor(path),status:'resolved',distribution:'hosted',storageKey:key,minecraftVersions:[bundle.minecraft],loaders:[bundle.loader.type]}));bundle.files=deduplicate(bundle.files).files;return saveRevision(id,revision,bundle,'add-local-file');}
export async function publishProject(id:string,input:unknown){const {revision,version,distributionConfirmed}=z.object({revision:z.number().int(),version:z.string().trim().min(1).max(100),distributionConfirmed:z.literal(true)}).parse(input);void distributionConfirmed;const project=await db.project.findUniqueOrThrow({where:{id}});if(project.revision!==revision)throw new ConflictException('Projeto mudou');const bundle=bundleSchema.parse(project.draft);const files=bundle.files.filter(f=>f.required);if(files.some(f=>f.status!=='resolved'||f.distribution==='blocked'))throw new BadRequestException('Resolva os arquivos obrigatórios antes de publicar');if(bundle.warnings.some(w=>w.startsWith('Dependência de runtime não suportada')))throw new BadRequestException('Dependência de runtime não suportada');if(!env.ANDROID_VALIDATED_TARGETS.some(t=>t.minecraft===bundle.minecraft&&t.loader===bundle.loader.type&&t.loaderVersion===bundle.loader.version))throw new BadRequestException('Esta combinação de Minecraft e loader ainda não foi homologada no Android');
  for(const file of files){if(!compatible(bundle,file))throw new BadRequestException(`Arquivo incompatível: ${file.name}`);if(file.distribution==='hosted'&&(!file.storageKey||!await hasObject(file.storageKey)))throw new BadRequestException(`Arquivo local ausente: ${file.name}`);}
  const releaseId=randomUUID();const manifest:ReleaseManifest={schemaVersion:1,projectId:id,releaseId,name:project.name,version,minecraft:bundle.minecraft,loader:bundle.loader,runtime:runtimeFor(bundle.minecraft),performance:bundle.performance,files:files.map(f=>({id:f.id,path:f.path,size:f.size,hashes:f.hashes,downloadEndpoint:`/api/v1/public/releases/${releaseId}/files/${encodeURIComponent(f.id)}/download`,provider:f.provider}))};
  return db.$transaction(async tx=>{const locked=await tx.project.updateMany({where:{id,revision},data:{updatedAt:new Date()}});if(!locked.count)throw new ConflictException('Projeto mudou');const release=await tx.release.create({data:{id:releaseId,projectId:id,version,bundle:json({...bundle,files}),manifest:json(manifest)}});await tx.audit.create({data:{action:'publish',entityId:releaseId,detail:json({projectId:id,revision})}});return release;});
}
export async function releaseDownload(releaseId:string,fileId:string){const release=await db.release.findUniqueOrThrow({where:{id:releaseId}});const file=bundleSchema.parse(release.bundle).files.find(f=>f.id===fileId);if(!file)throw new BadRequestException('Arquivo não pertence à release');if(file.distribution==='hosted'&&file.storageKey)return {url:await objectUrl(file.storageKey),expiresIn:900};let url=file.downloadUrl;if(file.provider==='curseforge'&&file.projectId&&file.versionId)url=await providers.curseforge.downloadUrl(file.projectId,file.versionId);if(!url)throw new BadRequestException('A origem não fornece download autorizado');const {safeDownloadUrl}=await import('../importer/download.js');await safeDownloadUrl(url);return {url,expiresIn:300};}
