import { z } from 'zod';
import type { Category, Dependency, ExternalProject, ExternalVersion, ModpackRepositoryProvider, ProviderImport, ResolvedFile, SearchQuery } from '@studio/core';
import { apiJson, ProviderError } from './http.js';
const loaders:Record<string,number>={forge:1,fabric:4,quilt:5,neoforge:6};
const file=z.object({id:z.number(),modId:z.number(),displayName:z.string(),fileName:z.string(),fileDate:z.string(),fileLength:z.number(),downloadUrl:z.string().nullable(),hashes:z.array(z.object({value:z.string(),algo:z.number()})),gameVersions:z.array(z.string()),dependencies:z.array(z.object({modId:z.number(),relationType:z.number()}))});
const project=z.object({id:z.number(),name:z.string(),slug:z.string(),summary:z.string(),downloadCount:z.number(),dateModified:z.string(),logo:z.object({url:z.string()}).nullable(),authors:z.array(z.object({name:z.string()})),screenshots:z.array(z.object({url:z.string()})),links:z.object({websiteUrl:z.string(),sourceUrl:z.string().nullable()}),categories:z.array(z.object({name:z.string()})),latestFiles:z.array(file),allowModDistribution:z.boolean().nullable().optional()});
export class CurseForgeModpackProvider implements ModpackRepositoryProvider {
  readonly id='curseforge' as const;
  constructor(private apiKey:string,private base='https://api.curseforge.com/v1'){}
  private async json<T>(path:string):Promise<T>{if(!this.apiKey)throw new ProviderError(this.id,503,'CurseForge não configurado: forneça CURSEFORGE_API_KEY');return (await apiJson<{data:T}>(this.id,`${this.base}${path}`,{'x-api-key':this.apiKey})).data;}
  private normalizeVersion(raw:unknown):ExternalVersion{const f=file.parse(raw);return {provider:this.id,projectId:String(f.modId),id:String(f.id),name:f.displayName,versionNumber:f.displayName,minecraftVersions:f.gameVersions.filter(v=>/^\d+\.\d+(\.\d+)?$/.test(v)),loaders:f.gameVersions.map(x=>x.toLowerCase()).filter(x=>x in loaders),publishedAt:f.fileDate,files:[{filename:f.fileName,url:f.downloadUrl,size:f.fileLength,hashes:Object.fromEntries(f.hashes.flatMap(h=>h.algo===1?[['sha1',h.value.toLowerCase()]]:h.algo===2?[['md5',h.value.toLowerCase()]]:[])),primary:true}],dependencies:f.dependencies.map(d=>({provider:this.id,projectId:String(d.modId),versionId:null,required:d.relationType===3,incompatible:d.relationType===5}))};}
  private normalizeProject(raw:unknown,description?:string):ExternalProject{const p=project.parse(raw);return {provider:this.id,externalProjectId:String(p.id),externalVersionId:null,name:p.name,slug:p.slug,icon:p.logo?.url??null,authors:p.authors.map(a=>a.name),minecraftVersions:[...new Set(p.latestFiles.flatMap(f=>f.gameVersions.filter(x=>/^\d+\.\d+(\.\d+)?$/.test(x))))],loaders:[...new Set(p.latestFiles.flatMap(f=>f.gameVersions.map(x=>x.toLowerCase()).filter(x=>x in loaders)))],downloads:p.downloadCount,followers:null,license:null,websiteUrl:p.links.websiteUrl,sourceUrl:p.links.sourceUrl,description:description??p.summary,descriptionFormat:description?'html':'text',summary:p.summary,gallery:p.screenshots.map(s=>s.url),categories:p.categories.map(c=>c.name),updatedAt:p.dateModified,modCount:null};}
  async searchModpacks(q:SearchQuery){if(!this.apiKey)throw new ProviderError(this.id,503,'CurseForge não configurado: forneça CURSEFORGE_API_KEY');const params=new URLSearchParams({gameId:'432',classId:q.type==='mod'?'6':'4471',searchFilter:q.query??'',index:String(q.offset??0),pageSize:String(q.limit??24),sortField:String(({popular:6,updated:3,newest:11,relevance:1})[q.sort??'popular']),sortOrder:'desc'});if(q.minecraft)params.set('gameVersion',q.minecraft);if(q.loader&&loaders[q.loader])params.set('modLoaderType',String(loaders[q.loader]));if(q.category)params.set('categoryId',q.category);const data=await apiJson<{data:unknown[];pagination:{totalCount:number;index:number;resultCount:number}}>(this.id,`${this.base}/mods/search?${params}`,{'x-api-key':this.apiKey});return {items:data.data.map(p=>this.normalizeProject(p)),total:data.pagination.totalCount,hasMore:data.pagination.index+data.pagination.resultCount<Math.min(10000,data.pagination.totalCount)};}
  async getModpack(projectId:string){return this.normalizeProject(await this.json(`/mods/${encodeURIComponent(projectId)}`),await this.json<string>(`/mods/${encodeURIComponent(projectId)}/description`));}
  async getVersions(projectId:string,q:SearchQuery={}):Promise<ExternalVersion[]>{const all:ExternalVersion[]=[];for(let index=0;index<10000;index+=50){const params=new URLSearchParams({index:String(index),pageSize:'50'});if(q.minecraft)params.set('gameVersion',q.minecraft);if(q.loader&&loaders[q.loader])params.set('modLoaderType',String(loaders[q.loader]));const page=z.array(file).parse(await this.json(`/mods/${encodeURIComponent(projectId)}/files?${params}`));all.push(...page.map(f=>this.normalizeVersion(f)));if(page.length<50)break;}return all.sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));}
  async getVersion(projectId:string,versionId:string){const v=this.normalizeVersion(await this.json(`/mods/${encodeURIComponent(projectId)}/files/${encodeURIComponent(versionId)}`));if(v.projectId!==projectId)throw new Error('Versão não pertence ao projeto');return v;}
  async downloadUrl(projectId:string,versionId:string):Promise<string|null>{const v=await this.getVersion(projectId,versionId);if(v.files[0]?.url)return v.files[0].url;try{return await this.json<string>(`/mods/${encodeURIComponent(projectId)}/files/${encodeURIComponent(versionId)}/download-url`);}catch(error){if(error instanceof ProviderError && [403,404].includes(error.status))return null;throw error;}}
  async getFiles(projectId:string,versionId:string):Promise<ResolvedFile[]>{const p=await this.getModpack(projectId),v=await this.getVersion(projectId,versionId);const url=await this.downloadUrl(projectId,versionId);return v.files.map(f=>({id:`curseforge:${projectId}:${versionId}`,provider:this.id,projectId,versionId,name:p.name,filename:f.filename,path:`mods/${f.filename}`,downloadUrl:url,downloads:url?[url]:[],hashes:f.hashes,size:f.size,required:true,environment:{client:'required',server:'required'},kind:'mod',distribution:url?'origin':'blocked',status:'pending',storageKey:null,issue:url?null:'Autor não disponibilizou download autorizado pela API',minecraftVersions:v.minecraftVersions,loaders:v.loaders,websiteUrl:p.websiteUrl,license:p.license,requiredBy:[]}));}
  async getDependencies(projectId:string,versionId:string):Promise<Dependency[]>{return (await this.getVersion(projectId,versionId)).dependencies;}
  async importModpack(input:ProviderImport){const v=await this.getVersion(input.projectId,input.versionId);if(v.files[0])v.files[0].url=await this.downloadUrl(input.projectId,input.versionId);return v;}
  async categories():Promise<Category[]>{const data=z.array(z.object({id:z.number(),name:z.string()})).parse(await this.json('/categories?gameId=432&classId=4471'));return data.map(c=>({id:String(c.id),name:c.name,provider:this.id}));}
}
