package net.kdt.pojavlaunch.studio;

import android.app.*;
import android.content.Context;
import android.text.InputType;
import android.widget.*;
import net.kdt.pojavlaunch.Tools;
import org.json.*;
import java.io.*;
import java.util.concurrent.Executor;

final class StudioPersonal {
    private final Activity activity;
    private final StudioApi api;
    private final Executor work;
    private final Runnable changed;
    StudioPersonal(Activity activity,StudioApi api,Executor work,Runnable changed){this.activity=activity;this.api=api;this.work=work;this.changed=changed;}
    private void message(String value){activity.runOnUiThread(()->Toast.makeText(activity,value,Toast.LENGTH_LONG).show());}
    private String owner(){return StudioAccount.read(activity).optJSONObject("player")==null?"legacy":StudioAccount.read(activity).optJSONObject("player").optString("id","legacy");}
    File cache(){return new File(activity.getFilesDir(),"studio-library-"+owner()+".json");}
    private File edits(){return new File(activity.getFilesDir(),"studio-profile-edits-"+owner()+".json");}
    private JSONObject pending(){try{File file=edits();if(file.isFile()&&file.length()<=262144)return new JSONObject(Tools.read(file.getPath()));}catch(Exception ignored){}return new JSONObject();}
    private void store(JSONObject values)throws Exception{if(values.toString().length()>131072)throw new IOException("Muitas alterações pendentes");java.nio.file.Path temp=java.nio.file.Files.createTempFile(activity.getFilesDir().toPath(),".profile-edits-",".tmp");try{java.nio.file.Files.write(temp,values.toString().getBytes("UTF-8"));java.nio.file.Files.move(temp,edits().toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING,java.nio.file.StandardCopyOption.ATOMIC_MOVE);}finally{java.nio.file.Files.deleteIfExists(temp);}}
    JSONObject library()throws Exception{
        StudioAccount.ensure(activity,api);JSONObject pending=pending();java.util.Iterator<String> ids=pending.keys();while(ids.hasNext()){String id=ids.next();try{api.post("/api/v1/player/profiles/"+id+"/settings",pending.getJSONObject(id));ids.remove();store(pending);}catch(StudioApi.ApiException error){if(error.status==409){message("Há alterações em outro aparelho. Use Resolver sincronização.");}else throw error;}}
        store(pending);JSONObject library=api.get("/api/v1/player/library");JSONArray profiles=library.getJSONArray("profiles");
        for(int i=0;i<profiles.length();i++){JSONObject p=profiles.getJSONObject(i),job=p.optJSONObject("job");if(p.isNull("card")&&job!=null&&"ready".equals(job.optString("status")))try{profiles.put(i,api.post("/api/v1/player/profiles/"+p.getString("id")+"/install",new JSONObject()));}catch(Exception error){p.put("preparationError",error.getMessage());}}
        return library;
    }
    void applyPending(JSONArray cards)throws Exception{JSONObject pending=pending();for(int i=0;i<cards.length();i++){JSONObject card=cards.getJSONObject(i),edit=pending.optJSONObject(card.optString("profileId"));if(edit!=null){card.put("name",edit.getString("name")).put("settings",edit.getJSONObject("settings")).put("favorite",edit.getBoolean("favorite"));}}}
    void account(){JSONObject session=StudioAccount.read(activity),player=session.optJSONObject("player");if(player!=null&&!player.optBoolean("guest",true)){
        new AlertDialog.Builder(activity).setTitle("Minha conta · "+player.optString("name")).setMessage(player.optString("email")+"\n\nPerfis e configurações ficam na sua biblioteca privada. Seus mundos permanecem no celular.").setPositiveButton("Fechar",null).setNegativeButton("Sair",(d,w)->work.execute(()->{try{api.post("/api/v1/player/auth/logout",new JSONObject());}catch(Exception ignored){}StudioAccount.clear(activity);activity.runOnUiThread(changed);})).setNeutralButton("Trocar senha",(d,w)->password()).show();return;}
        new AlertDialog.Builder(activity).setTitle("Salvar minha biblioteca").setMessage("Crie uma conta para recuperar seus perfis em outro celular. Você pode continuar como visitante e jogar offline o que já instalou.").setPositiveButton("Criar conta",(d,w)->credentials(true)).setNegativeButton("Já tenho conta",(d,w)->credentials(false)).setNeutralButton("Continuar como visitante",null).show();
    }
    private EditText input(String hint,boolean password){EditText e=new EditText(activity);e.setSingleLine(true);e.setHint(hint);if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}
    private LinearLayout form(){LinearLayout f=new LinearLayout(activity);f.setOrientation(1);f.setPadding(24,12,24,12);return f;}
    private void credentials(boolean register){LinearLayout form=form();EditText name=input("Seu nome",false),email=input("Email",false),password=input("Senha (mínimo 10 caracteres)",true);email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);if(register)form.addView(name);form.addView(email);form.addView(password);
        new AlertDialog.Builder(activity).setTitle(register?"Criar minha conta":"Entrar na minha conta").setView(form).setNegativeButton("Cancelar",null).setPositiveButton(register?"Criar conta":"Entrar",(d,w)->{final String n=name.getText().toString().trim(),e=email.getText().toString().trim(),p=password.getText().toString();work.execute(()->{try{JSONObject body=new JSONObject().put("email",e).put("password",p);if(register)body.put("name",n);StudioAccount.save(activity,api.post("/api/v1/player/auth/"+(register?"register":"login"),body));message("Conta conectada. Sincronizando sua biblioteca.");activity.runOnUiThread(changed);}catch(Exception error){message("Não foi possível entrar: "+error.getMessage());}});}).show();
    }
    private void password(){LinearLayout f=form();EditText current=input("Senha atual",true),next=input("Nova senha (mínimo 10 caracteres)",true);f.addView(current);f.addView(next);new AlertDialog.Builder(activity).setTitle("Trocar senha").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(d,w)->{String old=current.getText().toString(),value=next.getText().toString();work.execute(()->{try{StudioAccount.save(activity,api.post("/api/v1/player/auth/password",new JSONObject().put("currentPassword",old).put("password",value)));message("Senha alterada. Outras sessões foram encerradas.");}catch(Exception error){message(error.getMessage());}});}).show();}
    void settings(JSONObject card){if(!card.has("profileId")){work.execute(()->{try{StudioAccount.ensure(activity,api);api.post("/api/v1/player/profiles/from-release",new JSONObject().put("releaseId",card.getString("releaseId")));message("Perfil salvo na sua biblioteca.");activity.runOnUiThread(changed);}catch(Exception error){message(error.getMessage());}});return;}
        LinearLayout form=form();EditText name=input("Nome do perfil",false);name.setText(card.optString("name"));form.addView(name);CheckBox favorite=new CheckBox(activity);favorite.setText("Favorito");favorite.setChecked(card.optBoolean("favorite"));form.addView(favorite);
        Spinner performance=new Spinner(activity),touch=new Spinner(activity);performance.setAdapter(new ArrayAdapter<>(activity,android.R.layout.simple_spinner_dropdown_item,new String[]{"Leve · gráficos baixos","Equilibrado","Configurações originais"}));touch.setAdapter(new ArrayAdapter<>(activity,android.R.layout.simple_spinner_dropdown_item,new String[]{"Toque automático","Mostrar botões","Ocultar botões"}));JSONObject settings=card.optJSONObject("settings");String[] modes={"light","balanced","original"},controls={"auto","show","hide"};if(settings!=null){performance.setSelection(Math.max(0,java.util.Arrays.asList(modes).indexOf(settings.optString("performanceMode","light"))));touch.setSelection(Math.max(0,java.util.Arrays.asList(controls).indexOf(settings.optString("touchMode","auto"))));}form.addView(performance);form.addView(touch);
        new AlertDialog.Builder(activity).setTitle("Meu perfil").setView(form).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",(d,w)->{try{JSONObject edit=new JSONObject().put("revision",card.getInt("profileRevision")).put("name",name.getText().toString().trim()).put("favorite",favorite.isChecked()).put("settings",new JSONObject().put("performanceMode",modes[performance.getSelectedItemPosition()]).put("touchMode",controls[touch.getSelectedItemPosition()]));if(edit.getString("name").isEmpty()){message("Escolha um nome para o perfil");return;}work.execute(()->{try{JSONObject pending=pending();pending.put(card.getString("profileId"),edit);store(pending);activity.runOnUiThread(changed);}catch(Exception error){message(error.getMessage());}});}catch(Exception error){message(error.getMessage());}}).show();
    }
    void resolve(){JSONObject values=pending();if(values.length()==0){message("Nenhuma alteração pendente");return;}new AlertDialog.Builder(activity).setTitle("Resolver sincronização").setMessage("Você pode reaplicar suas configurações pendentes sobre a versão da nuvem ou descartar as alterações locais. Isso não altera os mundos.").setNegativeButton("Cancelar",null).setNeutralButton("Usar nuvem",(d,w)->work.execute(()->{try{store(new JSONObject());activity.runOnUiThread(changed);}catch(Exception error){message(error.getMessage());}})).setPositiveButton("Manter minhas alterações",(d,w)->work.execute(()->{try{JSONObject pending=pending();java.util.Iterator<String> ids=pending.keys();while(ids.hasNext()){String id=ids.next();JSONObject remote=api.get("/api/v1/player/profiles/"+id),edit=pending.getJSONObject(id);edit.put("revision",remote.getInt("revision"));api.post("/api/v1/player/profiles/"+id+"/settings",edit);ids.remove();store(pending);}activity.runOnUiThread(changed);}catch(Exception error){message(error.getMessage());}})).show();}
}
